version: '3.8'
services:
  appseed-app:
    container_name: flask_site
    restart: always
    env_file: .env
    build: .
    ports:
      - "5000:5000"
    networks:
      - flask_site

networks:
  flask_site:
    driver: bridge
